name: dreamer_playlist
description: A simple playlist.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  file_picker: ^5.5.0
  audioplayers: ^5.1.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true