name: dreamer_playlist
description: An audio player that allows you to play local audio files and create playlists.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  file_picker: ^8.1.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.1.0
  audio_service: ^0.18.12
  just_audio: ^0.9.35
  get_it: ^8.0.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true